source 'https://rubygems.org'

group :development, :test do
  gem 'rspec'
  gem 'pact', path: '../../'
  gem 'pact_broker-client'
  gem 'pry'
  # required for sbmt-pact
  gem 'combustion'
end

gem 'rake'

gem 'rack', '>= 3.1.5'
gem 'httparty', '>= 0.21.0'